//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryModelORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string Tradutor { get; set; }
        public System.DateTime Launch { get; set; }
        public Nullable<double> Price { get; set; }
        public string Language { get; set; }
        public string PublishingCompany { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
    }
}
